# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tomcatmanager}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hayato"]
  s.date = %q{2009-09-23}
  s.default_executable = %q{tomcatmanager}
  s.description = %q{frontend of Apache Tomcat manager application implemented by ruby}
  s.email = %q{haya10.ito+github@gmail.com}
  s.executables = ["tomcatmanager"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/tomcatmanager",
     "lib/tomcatmanager.rb",
     "spec/spec_helper.rb",
     "spec/tomcatmanager_spec.rb",
     "tomcatmanager.gemspec"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/hayato1980/tomcatmanager}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{frontend of Apache Tomcat manager application}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/tomcatmanager_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
